version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword  # รหัสผ่านของ root
      MYSQL_DATABASE: exampledb  # ชื่อฐานข้อมูลที่ต้องการสร้าง
      MYSQL_USER: user  # ชื่อผู้ใช้
      MYSQL_PASSWORD: userpassword  # รหัสผ่านของผู้ใช้
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mynetwork

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin_container
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: rootpassword
    ports:
      - "8080:80"
    networks:
      - mynetwork

volumes:
  mysql_data:

networks:
  mynetwork:
